### ISSUE TITLE
[Bug] Chat log displays single digit timestamps as a single digit

### ISSUE THREAD

**Issue by Venitel** [balkshamster/looperlands#166]
Heyo,
currently chat log in the game displays the timestamp in a HH:MM format (eg. 11:25). But if the timestamp contains a number thats only one digit, then only one digit will be displayed in that segment (eg. 3:7 instead of 03:07)

![chatlog2](https://github.com/balkshamster/looperlands/assets/37365074/d850d640-2fd6-411b-87a1-a471610e3b84)
![chatlog1](https://github.com/balkshamster/looperlands/assets/37365074/ef66fcb6-6363-4b7f-afa2-85bcc26cf522)

**Comment by balkshamster** [comment]
this should be fixed

**Comment by Venitel** [comment]
![obraz](https://github.com/balkshamster/looperlands/assets/37365074/61f5b782-537f-489d-a58b-c58b5651ab95)

Can confirm, we even got seconds as a bonus!
