### ISSUE TITLE
[Bug] Chat history window does not close if you attack a monster while its opened

### ISSUE THREAD

**Issue by Venitel** [balkshamster/looperlands#167]
Currently if you hit a blank enter in the chat input window, the chat history closes.
But if you follow the sequence:
1. Enter (open chat window)
2. Attack a monster
3. Blank enter (close chat window)

The chat history will not close.

https://github.com/balkshamster/looperlands/assets/37365074/078dc12c-f467-4afe-9517-9e29c5361e1e

On the vid first is correct and then incorrect behavior.

**Comment by balkshamster** [comment]
I think this is resolved now

**Comment by Venitel** [comment]
Yup - works flawlessly!
