### ISSUE TITLE
[Bug] Getting monster stuck and unable to attack

### ISSUE THREAD

**Issue by Venitel** [balkshamster/looperlands#168]
If both you and the monster are under an obstacle (wall), and you time&click on the same square just as the monster is approaching, you will end up on the samoe spot as him. 
The player continues to attack the monster, but the monster cannot attack the player. This makes pretty much any boss soloable, no matter how strong, as long as the damage is high enough to beat the HP regen.

https://github.com/balkshamster/looperlands/assets/37365074/a4822777-c58e-42c1-8f15-b3b508e1db72

**Comment by Venitel** [comment]
After some attempts and experience - it does appear that you can only get the mobs stuck on the southern (bottom) walls. He will never get stuck like this on the side or north ones

**Comment by Venitel** [comment]
https://github.com/balkshamster/looperlands/assets/37365074/9e5a1629-8127-4187-a2ba-94b7733aaf2c

Small update on the issue - I have noticed that no matter if it's the northern wall or the side walls, the default behavior for a mob (if you walk into him) is to step one tile to the bottom.
So if you do it near the bottom walls - he probably also tries to walk one tile down, but can't as there's a wall; that get's him stuck.

**Comment by balkshamster** [comment]
This issue should be resolved now

**Comment by Venitel** [comment]
Can confirm - after trying to reproduce many times, the boss always ended up attacking me back
