### ISSUE TITLE
wasd issues

### ISSUE THREAD

**Issue by balkshamster** [balkshamster/looperlands#375]
When WASD, character stops and then goes.

https://github.com/balkshamster/looperlands/assets/128100383/9a6fd7f4-ac89-4e40-9a28-d4fffbdcc953

**Comment by ordinaryadam** [comment]
Couple of highlights:
When moving it seems to cycle through the animation either too fast or skips over frames, this also happens on attacking
when you initially press to move using WSAD you move one tile, then it continues but there's a delay - leading to a disadvantage over mouse users.

**Comment by Venitel** [comment]
@balkshamster @ordinaryadam 
Regarding the delay after the first step - that's directly related to default windows keyboard delay settings

![obraz](https://github.com/balkshamster/looperlands/assets/37365074/336f9165-4fdb-4c62-be08-c25ead2d3d77)

Changing the repeat delay to Short fixes the issue - although it isn't a perfect solution to have to tell every player to adjust their windows settings.
I'm not sure if there's a clever way to fix it from the game's PoV - the windows is pretty much blocking the input so the game isn't aware that the key is being held down

**Comment by ordinaryadam** [comment]
Update - 

The issue with the animations being cut short appears to be related to holding the direction key down, if I'm in front of an enemy and tap the key towards them I fully animate my swing, if I hold it, it skips through the animation. light presses one at a time seems to do it.

suggestions

1) If there's a way to resolve holding the key down to attack, would be ideal
2) another option is to add an attack button, such as spacebar - not sure how feasible this is.

**Comment by Venitel** [comment]
Added a fix to the movement/attack delay in https://github.com/balkshamster/looperlands/pull/377

Also improved the way holding multiple buttons behaves - now moving diagonally should be smooth, and 2 opposite buttons cancel each other out (W+S = stand still)

The jittery animation remains unfixed - I have a few ideas but it may not be simple; leaving that one open for later as a lower prio
